
/* 关闭外键检测 */
SET FOREIGN_KEY_CHECKS = 0;

/* 系统用户 */
DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER` (
  
	`USERID` int(11) NOT NULL AUTO_INCREMENT,

	`USERNAME` varchar(50) NOT NULL COMMENT '用户名',
	`PASSWORD` varchar(128) NOT NULL,
	`NAME` varchar(50) NOT NULL,
  
	`DELFLAG` int(1) DEFAULT NULL,
  
	`DELTIME` datetime DEFAULT NULL,
  
	PRIMARY KEY (`USERID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统用户';

/* 系统角色 */
DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE `SYS_ROLE` (
	`ROLEID` int(8) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NOT NULL,
	`REMARK` varchar(100) NULL,
	`DELFLAG` int(1) DEFAULT NULL,
	`DELTIME` datetime DEFAULT NULL,
	PRIMARY KEY (`ROLEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统角色';

/* 用户-角色关系表 */
DROP TABLE IF EXISTS `SYS_USER_ROLE`;
CREATE TABLE `SYS_USER_ROLE` (
	`USERID` int(11) NOT NULL,
	`ROLEID` int(8) NOT NULL,
	KEY `ROLEID` (`ROLEID`),
	KEY `USERID` (`USERID`),
	CONSTRAINT `SYS_USER_ROLE_ROLEID` FOREIGN KEY (`ROLEID`) REFERENCES `SYS_ROLE` (`ROLEID`) ON DELETE CASCADE,
	CONSTRAINT `SYS_USER_ROLE_USERID` FOREIGN KEY (`USERID`) REFERENCES `SYS_USER` (`USERID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统用户-角色关系';

/* 菜单表 */
DROP TABLE IF EXISTS `SYS_MENU`;
CREATE TABLE `SYS_MENU` (
	`MENUID` int(8) NOT NULL AUTO_INCREMENT,
	`PID` int(8) NOT NULL,
	`ORDERID` int(4) NOT NULL,
	`MENUNAME` varchar(50) NOT NULL,
	`MURL` varchar(500) NULL,
	`ICON` varchar(50) NULL,
	`REMARK` varchar(100) NULL,
	`ISMENU` int(1) DEFAULT 1,
	`ENABLE` int(1) DEFAULT 1,
	PRIMARY KEY (`MENUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统菜单';

/* 权限功能表 */
DROP TABLE IF EXISTS `SYS_FUNCTION`;
CREATE TABLE `SYS_FUNCTION` (
	`FUNID` int(8) NOT NULL AUTO_INCREMENT,
	`MENUID` int(8) NOT NULL,
	`ORDERID` int(4) NOT NULL,
	`FUNKEY` varchar(50) NOT NULL,
	`FUNNAME` varchar(50) NOT NULL,
	PRIMARY KEY (`FUNID`),
	KEY `MENUID` (`MENUID`),
	CONSTRAINT `SYS_FUNCTION_MENUID` FOREIGN KEY (`MENUID`) REFERENCES `SYS_MENU` (`MENUID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='权限功能';

/* 功能URL表 */
DROP TABLE IF EXISTS `SYS_FUNCTION_URL`;
CREATE TABLE `SYS_FUNCTION_URL` (
	`URLID` int(8) NOT NULL AUTO_INCREMENT,
	`FUNID` int(8) NOT NULL,
	`UURL` varchar(500) NOT NULL,
	`ISLOG` int(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (`URLID`),
	KEY `FUNID` (`FUNID`),
	CONSTRAINT `SYS_FUNCTION_URL_FUNID` FOREIGN KEY (`FUNID`) REFERENCES `SYS_FUNCTION` (`FUNID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='功能URL';

/* 自由权限URL表 */
DROP TABLE IF EXISTS `SYS_FREE_URL`;
CREATE TABLE `SYS_FREE_URL` (
	`URLID` int(8) NOT NULL AUTO_INCREMENT,
	`REMARK` varchar(50) NOT NULL,
	`UURL` varchar(500) NOT NULL,
	PRIMARY KEY (`URLID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自由权限URL';

/* 角色-菜单关系表 */
DROP TABLE IF EXISTS `SYS_ROLE_MENU`;
CREATE TABLE `SYS_ROLE_MENU` (
	`ROLEID` int(8) NOT NULL,
	`MENUID` int(8) NOT NULL,
	KEY `ROLEID` (`ROLEID`),
	KEY `MENUID` (`MENUID`),
	CONSTRAINT `SYS_ROLE_MENU_ROLEID` FOREIGN KEY (`ROLEID`) REFERENCES `SYS_ROLE` (`ROLEID`) ON DELETE CASCADE,
	CONSTRAINT `SYS_ROLE_MENU_MENUID` FOREIGN KEY (`MENUID`) REFERENCES `SYS_MENU` (`MENUID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色-菜单关系';

/* 角色-功能关系表 */
DROP TABLE IF EXISTS `SYS_ROLE_FUNCTION`;
CREATE TABLE `SYS_ROLE_FUNCTION` (
	`ROLEID` int(8) NOT NULL,
	`FUNID` int(8) NOT NULL,
	KEY `ROLEID` (`ROLEID`),
	KEY `FUNID` (`FUNID`),
	CONSTRAINT `SYS_ROLE_FUNCTION_ROLEID` FOREIGN KEY (`ROLEID`) REFERENCES `SYS_ROLE` (`ROLEID`) ON DELETE CASCADE,
	CONSTRAINT `SYS_ROLE_FUNCTION_FUNID` FOREIGN KEY (`FUNID`) REFERENCES `SYS_FUNCTION` (`FUNID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色-功能关系';