/* 系统用户 */
DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER` (
  
	`USERID` varchar(50) NOT NULL,

	`USERNAME` varchar(50) NOT NULL,
	`PASSWORD` varchar(128) NOT NULL,
	`NAME` varchar(50) NOT NULL,
  
	`DELFLAG` int(1) DEFAULT NULL,
  
	`DELTIME` datetime DEFAULT NULL,
  
	PRIMARY KEY (`USERID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* 系统角色 */
DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE `SYS_ROLE` (
	`ROLEID` varchar(50) NOT NULL,
	`NAME` varchar(50) NOT NULL,
	`REMARK` varchar(100) NULL,
	`DELFLAG` int(1) DEFAULT NULL,
	`DELTIME` datetime DEFAULT NULL,
	PRIMARY KEY (`ROLEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* 菜单表 */
DROP TABLE IF EXISTS `SYS_MENU`;
CREATE TABLE `SYS_MENU` (
	`MENUID` int(8) NOT NULL,
	`PID` int(8) NOT NULL,
	`ORDERID` int(4) NOT NULL,
	`MENUNAME` varchar(50) NOT NULL,
	`MURL` varchar(500) NULL,
	`ICON` varchar(50) NULL,
	`REMARK` varchar(100) NULL,
	`ENABLE` int(1) DEFAULT 1,
	PRIMARY KEY (`MENUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;