/* 系统用户 */
DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER` (
  
	`USERID` varchar(50) NOT NULL,

	`USERNAME` varchar(50) NOT NULL,
	`PASSWORD` varchar(128) NOT NULL,
	`NAME` varchar(50) NOT NULL,
  
	`DELFLAG` int(1) DEFAULT NULL,
  
	`DELTIME` datetime DEFAULT NULL,
  
	PRIMARY KEY (`USERID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* 系统角色 */
DROP TABLE IF EXISTS `SYS_ROLE`;
CREATE TABLE `SYS_ROLE` (
	`ROLEID` varchar(50) NOT NULL,
	`NAME` varchar(50) NOT NULL,
	`REMARK` varchar(100) NULL,
	`DELFLAG` int(1) DEFAULT NULL,
	`DELTIME` datetime DEFAULT NULL,
	PRIMARY KEY (`ROLEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
