/* JBPM工作流扩展表 */
/* 关闭外键检测 */
SET FOREIGN_KEY_CHECKS = 0;

/* 流程类型 */
DROP TABLE IF EXISTS `JFLOW_TYPE`;
CREATE TABLE `JFLOW_TYPE` (
	`TYPEID` int(8) NOT NULL AUTO_INCREMENT,
	`PID` int(8) NOT NULL,
	`TYPENAME` varchar(50) NOT NULL COMMENT '类型名',
	PRIMARY KEY (`TYPEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='流程类型';