/* JBPM工作流扩展表 */
/* 关闭外键检测 */
SET FOREIGN_KEY_CHECKS = 0;

/* 流程类型 */
DROP TABLE IF EXISTS `JFLOW_TYPE`;
CREATE TABLE `JFLOW_TYPE` (
	`TYPEID` int(8) NOT NULL,
	`PID` int(8) NOT NULL,
	`TYPENAME` varchar(50) NOT NULL COMMENT '类型名',
	`TREECODE` text NOT NULL COMMENT '树编码',
	PRIMARY KEY (`TYPEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='流程类型';

/* 流程定义 */
DROP TABLE IF EXISTS `JFLOW_DEFINITION`;
CREATE TABLE `JFLOW_DEFINITION` (
	`DEFID` int(11) NOT NULL AUTO_INCREMENT,
	`TYPEID` int(8) NOT NULL,
	`NAME` varchar(50) NOT NULL COMMENT '名称',
	`DESCRIPTION` varchar(255) COMMENT '描述',
	`CREATETIME` datetime NOT NULL COMMENT '创建时间',
	`DEPLOYID` bigint(20) COMMENT '发布ID',
	`DEFXML` text NOT NULL COMMENT '定义XML',
	PRIMARY KEY (`DEFID`),
	KEY `TYPEID` (`TYPEID`),
	CONSTRAINT `JFLOW_DEFINITION_TYPEID` FOREIGN KEY (`TYPEID`) REFERENCES `JFLOW_TYPE` (`TYPEID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='流程定义';